### ISSUE TITLE
Transmission starts, then stops after about 1 second

### ISSUE THREAD

**Issue by WA6YDQ** [F5OEO/WsprryPi#3]
Running the following command:
> sudo wspr -n wa6ydq cm98 10 30m

Listening on 10.140, I can hear the transmission start. After a little less than 1 second, it stops transmitting. The program keeps running. This is the program output:
WSPR packet contents:
  Callsign: WA6YDQ
  Locator:  CM98
  Power:    10 dBm
Requested TX frequencies:
  10.140200 MHz
Extra options:
  NTP will be used to periodically calibrate the transmission frequency

Ready to transmit (setup complete)...
Desired center frequency for WSPR transmission: 10.140200 MHz
  Transmitting immediately (not waiting for WSPR window)
  Obtained new ppm value: 28.5143
  TX started at: UTC 2018-04-04 02:58:23.498
Channel 14 CBSize 2000 UsermemSize 1000
Using mbox device /dev/vcio.
68000 Size NUM PAGES 17 PAGE_SIZE 4096
BufferSize 1000 , cb 2000 user 1000
Info:NTP find ppm=28.514297
Info:NTP find ppm=28.514297
Info:NTP find ppm=28.514297
Freq = 1201723187
 multiplier:48.588458 divider:92 VCO: 932.9MHz
Master PLLA Locked
Clk Number 4 div 92 frac 0
Freq = 500000006
PCM prediv = 837
PCM clk=4091 / 2400

When I run the test tone the same thing happens:

> sudo wspr -n --test-tone 10140000
A test tone will be generated at frequency 10.140000 MHz
NTP will be used to calibrate the tone frequency

Info:NTP find ppm=28.514297
Freq = 1201698596
Transmitting test tone on frequency 10.140000 MHz
Press CTRL-C to exit!
 multiplier:48.587500 divider:92 VCO: 932.9MHz
Master PLLA Locked
Clk Number 4 div 92 frac 0

Transmission starts, the after a little less than 1 second, it stops. Program continues to run.

So far, 30M is the only band tested.

- kurt

**Comment by F5OEO** [comment]
Kurt, I just made some commits. Can you test with it ? What is your configuration system (Raspbian Lite version Stretch ou Jessie ?) : uname -a

**Comment by WA6YDQ** [comment]
Downloaded, re-built all. Deleted the 2 programs in /usr/local/bin, then ran sudo make install. Rebooted. Ran with no change. It still shuts off RF after a second.

> uname -a
Linux gadget 4.9.59+ #1047 Sun Oct 29 11:47:10 GMT 2017 armv6l GNU/Linux

I'm running a pi-0, not the w. Latest version of stretch, no other user-mode programs running.

> cat /boot/cmdline.txt
dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=1993bebd-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait modules-load=dwc2,g_ether

> sudo wspr -n wa6ydq cm98 10 10m
WSPR packet contents:
  Callsign: WA6YDQ
  Locator:  CM98
  Power:    10 dBm
Requested TX frequencies:
  28.126100 MHz
Extra options:
  NTP will be used to periodically calibrate the transmission frequency

Ready to transmit (setup complete)...
Desired center frequency for WSPR transmission: 28.126100 MHz
  Transmitting immediately (not waiting for WSPR window)
  TX started at: UTC 2018-04-04 15:18:15.070
Channel 14 CBSize 2000 UsermemSize 1000
Using mbox device /dev/vcio.
68000 Size NUM PAGES 17 PAGE_SIZE 4096
BufferSize 1000 , cb 2000 user 1000
Info:NTP find ppm=0.000000
Info:NTP find ppm=0.000000
Info:NTP find ppm=0.000000
Freq = 1200000000
 multiplier:42.482130 divider:29 VCO: 815.7MHz
Master PLLA Locked
Clk Number 4 div 29 frac 0
Freq = 1000000012
PCM clk=6849 / 1290
PCM Frequency out of range

I tried 30m, 20m, 15m, 10m. Above is the output of the 10m command. Starts up, then no output after a second or so. Program continues running.

I wonder if it is related to the new lib you wrote - I have the same problem running PiFmRds - on almost all frequencies it starts then shuts down, except on 91.5 MHz, where it runs correctly.

- kurt

**Comment by WA6YDQ** [comment]
And I am running raspbian lite (stretch).

- kurt

**Comment by WA6YDQ** [comment]
Just an update:

I am now using a new pi zero W with a different sd card and running stretch.
uname -a: Linux gadget2 4.14.62+ #1134 Tue Aug 14 16:58:07 BST 2018 armv6l GNU/Linux

I installed WsprryPi per instructions. When I run:
sudo wspr -t 146460e3 (146.460 mhz) I hear a tone for about half a second and the tone then stops, as before.

Edit: I am using I2C #1 to control a few devices (if that makes a difference). I also use I2S for audio playback.

I also installed rpitx and need the -a 14 option otherwise the pi zero stops and needs to be power cycled to come back to life. I don't see the -a option with WsprryPi. 
Is it needed?
-kurt

**Comment by F5OEO** [comment]
Add gpu_freq=250 in /boot/config.txt should fix the problem

**Comment by WA6YDQ** [comment]
No change. 

Here is part of my /boot/config.txt:

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on,i2c_arm_baudrate=400000

# for wspr (sw)
gpu_freq=250


# Enable audio (loads snd_bcm2835)
#dtparam=audio=on
dtoverlay=hifiberry-dac
dtoverlay=i2s-mmap


This is the output from a run:

pi@gadget2:~/src/WsprryPi $ sudo ./wspr wa6ydq cm98 10 2m
WSPR packet contents:
  Callsign: WA6YDQ
  Locator:  CM98
  Power:    10 dBm
Requested TX frequencies:
  144.490500 MHz
Extra options:
  NTP will be used to periodically calibrate the transmission frequency

Ready to transmit (setup complete)...
Desired center frequency for WSPR transmission: 144.490500 MHz
  Waiting for next WSPR transmission window...
  Obtained new ppm value: 0.412796
  TX started at: UTC 2018-11-09 02:40:01.003
Channel 14 CBSize 2000 UsermemSize 1000
Using mbox device /dev/vcio.
68000 Size NUM PAGES 17 PAGE_SIZE 4096
BufferSize 1000 , cb 2000 user 1000
Info:NTP find ppm=0.412796
Info:NTP find ppm=0.412796
Info:NTP find ppm=0.412796
Freq = 1000000012
 multiplier:60.204375 divider:8 VCO: 1155.9MHz Spurious 0.000000 
Master PLLC Locked
Clk Number 5 div 8 frac 0
Freq = 1000000012
PCM clk=6849 / 1290
PCM Frequency out of range
Freq resolution=2.288818 - Tone spacing =1.464844 Erreur tuning=-1.647949


The transmission started, then locked up. A power cycle was required to restore the computer.

This is a pi zero w. I deleted all previous references to rpitx, WsprryPi, librpitx  etc and did a fresh install per your instructions.

I tried again from the console, and after WsprryPi started, the screen scrolled up (very fast, could not see any error messages) and the kernel stopped responding to all input. A power cycle was required to restore the computer.

Any more information I can provide?

- Kurt

**Comment by F5OEO** [comment]
I2S confilcting with rpitx. For Wspr, I set it to use PWM to avoid it. Please test with latest commits (both Wsprpi  and librpitx)

**Comment by WA6YDQ** [comment]
That seemed to fix it. When using a USB keyboard/hdmi for display, the WsprrPi program runs as expected. Thank you for putting the time into this! 

One small issue - after WrprrPi completes sending a transmission, the wifi on the pi zero stops. Only a problem when connecting to it via ssh thru wifi.

I get these errors from /var/log/kern.log:

Nov 17 13:16:53 gadget2 kernel: [  243.406210] brcmfmac: brcmf_sdio_hostmail: Unknown mailbox data content: 0x40012
Nov 17 13:18:14 gadget2 kernel: [  323.680792] brcmfmac: brcmf_sdio_bus_rxctl: resumed on timeout
Nov 17 13:18:14 gadget2 kernel: [  323.684677] brcmfmac: brcmf_sdio_checkdied: firmware trap in dongle
Nov 17 13:18:16 gadget2 kernel: [  326.240777] brcmfmac: brcmf_sdio_bus_rxctl: resumed on timeout
Nov 17 13:18:16 gadget2 kernel: [  326.244626] brcmfmac: brcmf_sdio_checkdied: firmware trap in dongle
Nov 17 13:18:16 gadget2 kernel: [  326.244656] brcmfmac: brcmf_cfg80211_get_station: GET STA INFO failed, -110
Nov 17 13:18:19 gadget2 kernel: [  328.800996] brcmfmac: brcmf_sdio_bus_rxctl: resumed on timeout
Nov 17 13:18:19 gadget2 kernel: [  328.804827] brcmfmac: brcmf_sdio_checkdied: firmware trap in dongle
Nov 17 13:18:21 gadget2 kernel: [  331.150760] brcmfmac: brcmf_cfg80211_get_station: GET STA INFO failed, -512
Nov 17 13:19:08 gadget2 kernel: [  378.320557] brcmfmac: brcmf_proto_bcdc_query_dcmd: brcmf_proto_bcdc_msg failed w/status -110
Nov 17 13:19:11 gadget2 kernel: [  380.880539] brcmfmac: brcmf_proto_bcdc_query_dcmd: brcmf_proto_bcdc_msg failed w/status -110
Nov 17 13:19:11 gadget2 kernel: [  380.880564] brcmfmac: brcmf_cfg80211_get_station: GET STA INFO failed, -110
Nov 17 13:19:13 gadget2 kernel: [  383.440528] brcmfmac: brcmf_proto_bcdc_query_dcmd: brcmf_proto_bcdc_msg failed w/status -110
Nov 17 13:19:16 gadget2 kernel: [  386.000521] brcmfmac: brcmf_proto_bcdc_query_dcmd: brcmf_proto_bcdc_msg failed w/status -110
Nov 17 13:19:16 gadget2 kernel: [  386.000545] brcmfmac: brcmf_cfg80211_get_station: GET STA INFO failed, -110
Nov 17 13:19:19 gadget2 kernel: [  388.560507] brcmfmac: brcmf_proto_bcdc_query_dcmd: brcmf_proto_bcdc_msg failed w/status -110
Nov 17 13:19:19 gadget2 kernel: [  388.560534] brcmfmac: brcmf_cfg80211_get_tx_power: error (-110)
Nov 17 13:29:58 gadget2 kernel: [ 1028.397553] brcmfmac: brcmf_vif_set_mgmt_ie: vndr ie set error : -110
Nov 17 13:29:58 gadget2 kernel: [ 1028.397579] brcmfmac: brcmf_cfg80211_scan: scan error (-110)


I am only using the built-in wifi. The only active usb device is a 32GB usb flash drive. I2S is not active nor is any I2C devices.

- kurt
