### ISSUE TITLE
PCM Frequency out of range

### ISSUE THREAD

**Issue by ZS6RAS** [F5OEO/WsprryPi#4]
Please can you help me.

I installed WsprryPi yesterday and every time I try and run a transmission this is what I get: 

 sudo ./wspr --repeat --offset --self-calibration ZS6RAS KG44 20 40m
WSPR packet contents:
  Callsign: ZS6RAS
  Locator:  KG44
  Power:    20 dBm
Requested TX frequencies:
  7.040100 MHz
Extra options:
  NTP will be used to periodically calibrate the transmission frequency
  Transmissions will continue forever until stopped with CTRL-C
  A small random frequency offset will be added to all transmissions

Ready to transmit (setup complete)...
Desired center frequency for WSPR transmission: 7.040035 MHz
  Waiting for next WSPR transmission window...
  Obtained new ppm value: -6.20636
  TX started at: UTC 2018-07-08 08:50:01.000
Channel 14 CBSize 2000 UsermemSize 1000
Using mbox device /dev/vcio.
68000 Size NUM PAGES 17 PAGE_SIZE 4096
BufferSize 1000 , cb 2000 user 1000
Info:NTP find ppm=-6.206360
Info:NTP find ppm=-6.206360
Info:NTP find ppm=-6.206360
Freq = 1000000012
Master PLLA Locked
Clk Number 4 div 133 frac 0
Freq = 1000000012
PCM clk=6849 / 1290
PCM Frequency out of range

I am using a Raspberry Pi Model 3B and RASPBIAN STRETCH LITE.

**Comment by F5OEO** [comment]
Here is my output : 
sudo ./wspr --repeat --offset --self-calibration ZS6RAS KG44 20 40m
WSPR packet contents:
  Callsign: ZS6RAS
  Locator:  KG44
  Power:    20 dBm
Requested TX frequencies:
  7.040100 MHz
Extra options:
  NTP will be used to periodically calibrate the transmission frequency
  Transmissions will continue forever until stopped with CTRL-C
  A small random frequency offset will be added to all transmissions

Ready to transmit (setup complete)...
Desired center frequency for WSPR transmission: 7.040141 MHz
  Waiting for next WSPR transmission window...
  Obtained new ppm value: -4.13478
  TX started at: UTC 2018-07-08 13:42:01.001
Channel 14 CBSize 2000 UsermemSize 1000
Using mbox device /dev/vcio.
68000 Size NUM PAGES 17 PAGE_SIZE 4096
BufferSize 1000 , cb 2000 user 1000
Info:NTP find ppm=-4.134781
Info:NTP find ppm=-4.134781
Info:NTP find ppm=-4.134781
Freq = 929280560
Master PLLA Locked
Clk Number 4 div 133 frac 0
Freq = 500000006
PCM prediv = 837
PCM clk=4091 / 2400

It seems that PLLD is at 1ghz instead of 500Mhz.
Maybe you have mixed with rpitx master branch which modify PLLD frequency(use v2beta of rpitx).
Solution is to remove /boot/dtblob.bin : sudo rm /boot/dtblob.bin

Let me know.

**Comment by ZS6RAS** [comment]
I have removed the dt-blob.bin file from /boot but still have the same issue. Is there anything else I can try?

**Comment by ZS6RAS** [comment]
Sorry I looks like it worked after a reboot. Here is what I ran, does this mean it is working?

sudo ./wspr --repeat --offset --self-calibration ZS6RAS KG44 10 40m
WSPR packet contents:
  Callsign: ZS6RAS
  Locator:  KG44
  Power:    10 dBm
Requested TX frequencies:
  7.040100 MHz
Extra options:
  NTP will be used to periodically calibrate the transmission frequency
  Transmissions will continue forever until stopped with CTRL-C
  A small random frequency offset will be added to all transmissions

Ready to transmit (setup complete)...
Desired center frequency for WSPR transmission: 7.040045 MHz
  Waiting for next WSPR transmission window...
  Obtained new ppm value: -1.14459
  TX started at: UTC 2018-07-08 14:52:01.001
Channel 14 CBSize 2000 UsermemSize 1000
Using mbox device /dev/vcio.
68000 Size NUM PAGES 17 PAGE_SIZE 4096
BufferSize 1000 , cb 2000 user 1000
Info:NTP find ppm=-1.144592
Info:NTP find ppm=-1.144592
Info:NTP find ppm=-1.144592
Freq = 1000000012
Master PLLA Locked
Clk Number 4 div 133 frac 0
Freq = 500000006
PCM prediv = 837
PCM clk=4091 / 2400

^ZExiting with error; caught signal: 20

**Comment by F5OEO** [comment]
Yes, should Be OK. Have you try to décodé output?

**Comment by ZS6RAS** [comment]
Yes and it decoded. But only once. Is it normal that it is non stop transmitting? WSJT-X transmits from 0 to 110sec.

**Comment by ZS6RAS** [comment]
### This is what I get when I transmit and only decode once:

 sudo ./wspr --repeat --offset --self-calibration ZS6RAS KG44 10 40m 0
WSPR packet contents:
  Callsign: ZS6RAS
  Locator:  KG44
  Power:    10 dBm
Requested TX frequencies:
  7.040100 MHz
  0.000000 MHz
Extra options:
  NTP will be used to periodically calibrate the transmission frequency
  Transmissions will continue forever until stopped with CTRL-C
  A small random frequency offset will be added to all transmissions

Ready to transmit (setup complete)...
Desired center frequency for WSPR transmission: 7.040088 MHz
  Waiting for next WSPR transmission window...
  Obtained new ppm value: -2.26683
  TX started at: UTC 2018-07-08 18:00:01.869
Channel 14 CBSize 2000 UsermemSize 1000
Using mbox device /dev/vcio.
68000 Size NUM PAGES 17 PAGE_SIZE 4096
BufferSize 1000 , cb 2000 user 1000
Info:NTP find ppm=-2.266830
Info:NTP find ppm=-2.266830
Info:NTP find ppm=-2.266830
Freq = 1000000012
Master PLLA Locked
Clk Number 4 div 133 frac 0
Freq = 500000006
PCM prediv = 837
PCM clk=4091 / 2400
  TX ended at:   UTC 2018-07-08 18:01:48.297 (106.428 s)
Desired center frequency for WSPR transmission: 0.000000 MHz
  Waiting for next WSPR transmission window...
  Skipping transmission
Desired center frequency for WSPR transmission: 7.040044 MHz
  Waiting for next WSPR transmission window...
  TX started at: UTC 2018-07-08 18:04:01.001

^ZExiting with error; caught signal: 20

### And then it just hangs at TX started at: UTC 2018-07-08 18:04:01.001 and does not do anything further.

**Comment by ZS6RAS** [comment]
### This is what I get when I transmit and only decode once:
sudo ./wspr --repeat --offset --self-calibration ZS6RAS KG44 10 40m 0
WSPR packet contents:
Callsign: ZS6RAS
Locator: KG44
Power: 10 dBm
Requested TX frequencies:
7.040100 MHz
0.000000 MHz
Extra options:
NTP will be used to periodically calibrate the transmission frequency
Transmissions will continue forever until stopped with CTRL-C
A small random frequency offset will be added to all transmissions

Ready to transmit (setup complete)...
Desired center frequency for WSPR transmission: 7.040088 MHz
Waiting for next WSPR transmission window...
Obtained new ppm value: -2.26683
TX started at: UTC 2018-07-08 18:00:01.869
Channel 14 CBSize 2000 UsermemSize 1000
Using mbox device /dev/vcio.
68000 Size NUM PAGES 17 PAGE_SIZE 4096
BufferSize 1000 , cb 2000 user 1000
Info:NTP find ppm=-2.266830
Info:NTP find ppm=-2.266830
Info:NTP find ppm=-2.266830
Freq = 1000000012
Master PLLA Locked
Clk Number 4 div 133 frac 0
Freq = 500000006
PCM prediv = 837
PCM clk=4091 / 2400
TX ended at: UTC 2018-07-08 18:01:48.297 (106.428 s)
Desired center frequency for WSPR transmission: 0.000000 MHz
Waiting for next WSPR transmission window...
Skipping transmission
Desired center frequency for WSPR transmission: 7.040044 MHz
Waiting for next WSPR transmission window...
TX started at: UTC 2018-07-08 18:04:01.001

^ZExiting with error; caught signal: 20

### And then it just hangs at TX started at: UTC 2018-07-08 18:04:01.001 and does not do anything further.

**Comment by F5OEO** [comment]
Repeat is fixed with https://github.com/F5OEO/WsprryPi/commit/42f2a8b0018d3d683e16aee05ef733a8c2464aab
