### ISSUE TITLE
Raspian Buster - strange behaviour - frequency is some kHz off - sends always on first band

### ISSUE THREAD

**Issue by hubertmeier** [F5OEO/WsprryPi#6]
Hi,

yesterday i was looking for another repo because i installed the new raspian buster on a pi 3b+ on which i used WsprryPi from JamesP6000 which was pretty ok. After installing a fresh raspian buster the compiler stopped with an error: undefined reference to 'makedev'

Your version seems to be newer, so i tried this. The compiler works, i see the error shortly but only as warning.

If i start with the same command line like this:
sudo /home/pi/WsprryPi/wspr --repeat --self-calibration DO7TIM JN39 10 10m 15m

the output seems to be ok, but the transmission is only 10m even if the frequency shows 15m ! The frequency is about 3 kHz off, the entry gpu_freq was done and i installed ntp and ntpstat.
I have a kiwi-SDR, so i can see what the raspi does.

Desired center frequency for WSPR transmission: 28.126100 MHz **<- OK**
  Waiting for next WSPR transmission window...
  TX started at: UTC 2019-06-26 15:24:01.001
  TX ended at:   UTC 2019-06-26 15:25:52.638 (111.637 s)
Desired center frequency for WSPR transmission: 21.096100 MHz **<- sends 10m too**
  Waiting for next WSPR transmission window...
  TX started at: UTC 2019-06-26 15:26:01.000
  TX ended at:   UTC 2019-06-26 15:27:51.418 (110.417 s)
Desired center frequency for WSPR transmission: 28.126100 MHz
  Waiting for next WSPR transmission window...
  TX started at: UTC 2019-06-26 15:28:01.000

i use a combined 10m/15m-Antenna and bandpass-filter

Thank you

**Comment by F5OEO** [comment]
Issue should be fixed with https://github.com/F5OEO/WsprryPi/commit/58a6fc6375f5f3a54ee5864e6c06ee80919b2929
