### ISSUE TITLE
Frequency hopping is not working

### ISSUE THREAD

**Issue by HS2JFW** [F5OEO/WsprryPi#7]
In original code, band hopping is not working.
I have change the code to the following to make it work.

***** wspr.cpp: Original *****************************************************

if(ngfmtest==NULL)
{
   ngfmtest=new ngfmdmasync(center_freq_actual,SR,14,FifoSize,true);
  FreqPWM=(float*)malloc(Upsample*sizeof(float));
}
else
   ngfmtest->enableclk(4);

***** wspr.cpp: Changed *****************************************************

  ngfmtest=new ngfmdmasync(center_freq_actual,SR,14,FifoSize,true);
  FreqPWM=(float*)malloc(Upsample*sizeof(float));
  ngfmtest->enableclk(4);

And also add call cleanup(); function at the end of tx.

// Turn transmitter off
  ngfmtest->disableclk(4);
  cleanup();

Still unknown other issue after this modification.

Hope this help.

73 Joe
HS2JFW

**Comment by F5OEO** [comment]
Thanks...issue should be fixed with https://github.com/F5OEO/WsprryPi/commit/58a6fc6375f5f3a54ee5864e6c06ee80919b2929
